version: '3.9'
services:
  servicestack-docs-search:
    image: ghcr.io/servicestack/docs-search:latest
    restart: always
    networks:
      - kamal
    environment:
      TYPESENSE_API_KEY: "${TYPESENSE_API_KEY}"
    command:
      - "--data-dir"
      - "/data"
      - "--api-key"
      - "${TYPESENSE_API_KEY}"
      - "--enable-cors"

networks:
  kamal:
    external: true

